import type { Document, Employee } from "../hooks/useQueries";

export const SAMPLE_EMPLOYEES: Employee[] = [
  {
    id: 1n,
    name: "Rajesh Kumar",
    aadhaarNumber: "1234-5678-9001",
    photo: "",
    designation: "Site Manager",
    workName: "Acme Construction",
    workSite: "Site A",
    employmentStatus: "Working",
    email: "rajesh.kumar@acme.com",
  },
  {
    id: 2n,
    name: "Priya Sharma",
    aadhaarNumber: "2345-6789-0012",
    photo: "",
    designation: "Civil Engineer",
    workName: "Acme Construction",
    workSite: "Site A",
    employmentStatus: "Working",
    email: "priya.sharma@acme.com",
  },
  {
    id: 3n,
    name: "Mohammed Irfan",
    aadhaarNumber: "3456-7890-1123",
    photo: "",
    designation: "Foreman",
    workName: "Bridge Works",
    workSite: "Site B",
    employmentStatus: "Working",
    email: "mohammed.irfan@bridgeworks.com",
  },
  {
    id: 4n,
    name: "Anita Desai",
    aadhaarNumber: "4567-8901-2234",
    photo: "",
    designation: "Safety Supervisor",
    workName: "Bridge Works",
    workSite: "Site B",
    employmentStatus: "Working",
    email: "anita.desai@bridgeworks.com",
  },
  {
    id: 5n,
    name: "Suresh Nair",
    aadhaarNumber: "5678-9012-3345",
    photo: "",
    designation: "Structural Engineer",
    workName: "Bridge Works",
    workSite: "North Zone",
    employmentStatus: "Working",
    email: "suresh.nair@bridgeworks.com",
  },
  {
    id: 6n,
    name: "Kavita Reddy",
    aadhaarNumber: "6789-0123-4456",
    photo: "",
    designation: "Labour Supervisor",
    workName: "Road Division",
    workSite: "North Zone",
    employmentStatus: "Left",
    email: "kavita.reddy@roaddiv.com",
  },
  {
    id: 7n,
    name: "Vikram Singh",
    aadhaarNumber: "7890-1234-5567",
    photo: "",
    designation: "Project Manager",
    workName: "Road Division",
    workSite: "Site A",
    employmentStatus: "Working",
    email: "vikram.singh@roaddiv.com",
  },
  {
    id: 8n,
    name: "Deepa Menon",
    aadhaarNumber: "8901-2345-6678",
    photo: "",
    designation: "Accountant",
    workName: "Acme Construction",
    workSite: "Site B",
    employmentStatus: "Working",
    email: "deepa.menon@acme.com",
  },
  {
    id: 9n,
    name: "Ravi Pillai",
    aadhaarNumber: "9012-3456-7789",
    photo: "",
    designation: "Electrician",
    workName: "Road Division",
    workSite: "North Zone",
    employmentStatus: "Left",
    email: "ravi.pillai@roaddiv.com",
  },
  {
    id: 10n,
    name: "Sneha Joshi",
    aadhaarNumber: "0123-4567-8890",
    photo: "",
    designation: "HR Coordinator",
    workName: "Acme Construction",
    workSite: "Site A",
    employmentStatus: "Working",
    email: "sneha.joshi@acme.com",
  },
];

export const SAMPLE_DOCUMENTS: Document[] = [
  // Rajesh Kumar – Acme Construction
  {
    id: 101n,
    employeeId: 1n,
    title: "Aadhaar Card – Rajesh Kumar",
    category: "Aadhaar Card",
    status: "Active",
    fileType: "img",
    uploadDate: "2024-01-15",
    expiryDate: "",
  },
  {
    id: 102n,
    employeeId: 1n,
    title: "Employment Contract 2024",
    category: "Contract",
    status: "Active",
    fileType: "pdf",
    uploadDate: "2024-01-20",
    expiryDate: "2026-01-20",
  },
  {
    id: 103n,
    employeeId: 1n,
    title: "Bank Account Details – Rajesh Kumar",
    category: "Bank Details",
    status: "Active",
    fileType: "pdf",
    uploadDate: "2024-01-20",
    expiryDate: "",
  },
  {
    id: 104n,
    employeeId: 1n,
    title: "Employee Photo – Rajesh Kumar",
    category: "Employee Photo",
    status: "Active",
    fileType: "img",
    uploadDate: "2024-01-10",
    expiryDate: "",
  },

  // Priya Sharma – Acme Construction
  {
    id: 201n,
    employeeId: 2n,
    title: "Aadhaar Card – Priya Sharma",
    category: "Aadhaar Card",
    status: "Active",
    fileType: "img",
    uploadDate: "2024-02-05",
    expiryDate: "",
  },
  {
    id: 202n,
    employeeId: 2n,
    title: "Offer Letter – Civil Engineer",
    category: "Offer Letter",
    status: "Approved",
    fileType: "pdf",
    uploadDate: "2023-11-01",
    expiryDate: "",
  },
  {
    id: 203n,
    employeeId: 2n,
    title: "Civil Engineering Certificate",
    category: "Certificate",
    status: "Active",
    fileType: "pdf",
    uploadDate: "2024-05-20",
    expiryDate: "2027-05-20",
  },
  {
    id: 204n,
    employeeId: 2n,
    title: "January 2025 Payslip",
    category: "Payslip",
    status: "Active",
    fileType: "pdf",
    uploadDate: "2025-01-31",
    expiryDate: "",
  },

  // Mohammed Irfan – Bridge Works
  {
    id: 301n,
    employeeId: 3n,
    title: "Aadhaar Card – Mohammed Irfan",
    category: "Aadhaar Card",
    status: "Active",
    fileType: "img",
    uploadDate: "2024-03-10",
    expiryDate: "",
  },
  {
    id: 302n,
    employeeId: 3n,
    title: "Employment Agreement",
    category: "Contract",
    status: "Active",
    fileType: "doc",
    uploadDate: "2022-08-15",
    expiryDate: "2025-08-15",
  },
  {
    id: 303n,
    employeeId: 3n,
    title: "Safety Training Certificate",
    category: "Certificate",
    status: "Active",
    fileType: "pdf",
    uploadDate: "2023-09-01",
    expiryDate: "2026-09-01",
  },

  // Anita Desai – Bridge Works
  {
    id: 401n,
    employeeId: 4n,
    title: "Aadhaar Card – Anita Desai",
    category: "Aadhaar Card",
    status: "Active",
    fileType: "img",
    uploadDate: "2023-04-20",
    expiryDate: "",
  },
  {
    id: 402n,
    employeeId: 4n,
    title: "Safety Supervisor Offer Letter",
    category: "Offer Letter",
    status: "Approved",
    fileType: "pdf",
    uploadDate: "2023-04-01",
    expiryDate: "",
  },
  {
    id: 403n,
    employeeId: 4n,
    title: "OSHA Safety Certificate",
    category: "Certificate",
    status: "Active",
    fileType: "pdf",
    uploadDate: "2024-07-15",
    expiryDate: "2027-07-15",
  },

  // Suresh Nair – Bridge Works
  {
    id: 501n,
    employeeId: 5n,
    title: "Aadhaar Card – Suresh Nair",
    category: "Aadhaar Card",
    status: "Active",
    fileType: "img",
    uploadDate: "2024-06-01",
    expiryDate: "",
  },
  {
    id: 502n,
    employeeId: 5n,
    title: "Structural Engineer Contract",
    category: "Contract",
    status: "Active",
    fileType: "pdf",
    uploadDate: "2024-06-15",
    expiryDate: "2026-06-15",
  },
  {
    id: 503n,
    employeeId: 5n,
    title: "Bank Account Details – Suresh Nair",
    category: "Bank Details",
    status: "Active",
    fileType: "pdf",
    uploadDate: "2024-06-01",
    expiryDate: "",
  },
  {
    id: 504n,
    employeeId: 5n,
    title: "January 2025 Payslip",
    category: "Payslip",
    status: "Active",
    fileType: "pdf",
    uploadDate: "2025-01-31",
    expiryDate: "",
  },

  // Kavita Reddy – Road Division (Left)
  {
    id: 601n,
    employeeId: 6n,
    title: "Aadhaar Card – Kavita Reddy",
    category: "Aadhaar Card",
    status: "Active",
    fileType: "img",
    uploadDate: "2024-09-01",
    expiryDate: "",
  },
  {
    id: 602n,
    employeeId: 6n,
    title: "Relieving Letter",
    category: "Contract",
    status: "Approved",
    fileType: "pdf",
    uploadDate: "2025-01-05",
    expiryDate: "",
  },

  // Vikram Singh – Road Division
  {
    id: 701n,
    employeeId: 7n,
    title: "Aadhaar Card – Vikram Singh",
    category: "Aadhaar Card",
    status: "Active",
    fileType: "img",
    uploadDate: "2023-11-10",
    expiryDate: "",
  },
  {
    id: 702n,
    employeeId: 7n,
    title: "Project Manager Offer Letter",
    category: "Offer Letter",
    status: "Approved",
    fileType: "pdf",
    uploadDate: "2023-10-25",
    expiryDate: "",
  },
  {
    id: 703n,
    employeeId: 7n,
    title: "PMP Certification",
    category: "Certificate",
    status: "Active",
    fileType: "pdf",
    uploadDate: "2024-03-15",
    expiryDate: "2027-03-15",
  },

  // Deepa Menon – Acme Construction
  {
    id: 801n,
    employeeId: 8n,
    title: "Aadhaar Card – Deepa Menon",
    category: "Aadhaar Card",
    status: "Active",
    fileType: "img",
    uploadDate: "2024-07-01",
    expiryDate: "",
  },
  {
    id: 802n,
    employeeId: 8n,
    title: "Accountant Contract",
    category: "Contract",
    status: "Active",
    fileType: "doc",
    uploadDate: "2025-02-18",
    expiryDate: "2027-02-18",
  },
  {
    id: 803n,
    employeeId: 8n,
    title: "Bank Account Details – Deepa Menon",
    category: "Bank Details",
    status: "Active",
    fileType: "pdf",
    uploadDate: "2024-07-05",
    expiryDate: "",
  },

  // Ravi Pillai – Road Division (Left)
  {
    id: 901n,
    employeeId: 9n,
    title: "Aadhaar Card – Ravi Pillai",
    category: "Aadhaar Card",
    status: "Active",
    fileType: "img",
    uploadDate: "2024-04-10",
    expiryDate: "",
  },
  {
    id: 902n,
    employeeId: 9n,
    title: "Electrician Offer Letter",
    category: "Offer Letter",
    status: "Approved",
    fileType: "pdf",
    uploadDate: "2024-04-01",
    expiryDate: "",
  },
  {
    id: 903n,
    employeeId: 9n,
    title: "Electrical Safety Certificate",
    category: "Certificate",
    status: "Expired",
    fileType: "pdf",
    uploadDate: "2024-09-10",
    expiryDate: "2025-09-10",
  },

  // Sneha Joshi – Acme Construction
  {
    id: 1001n,
    employeeId: 10n,
    title: "Aadhaar Card – Sneha Joshi",
    category: "Aadhaar Card",
    status: "Active",
    fileType: "img",
    uploadDate: "2023-08-20",
    expiryDate: "",
  },
  {
    id: 1002n,
    employeeId: 10n,
    title: "HR Coordinator Contract",
    category: "Contract",
    status: "Active",
    fileType: "pdf",
    uploadDate: "2023-08-01",
    expiryDate: "2026-08-01",
  },
  {
    id: 1003n,
    employeeId: 10n,
    title: "Employee Photo – Sneha Joshi",
    category: "Employee Photo",
    status: "Active",
    fileType: "img",
    uploadDate: "2023-08-01",
    expiryDate: "",
  },
  {
    id: 1004n,
    employeeId: 10n,
    title: "January 2025 Payslip",
    category: "Payslip",
    status: "Active",
    fileType: "pdf",
    uploadDate: "2025-01-31",
    expiryDate: "",
  },
];
