/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdminUser = IDL.Record({
  'id' : IDL.Nat,
  'password' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Document = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'expiryDate' : IDL.Text,
  'fileType' : IDL.Text,
  'employeeId' : IDL.Nat,
  'category' : IDL.Text,
  'uploadDate' : IDL.Text,
});
export const Employee = IDL.Record({
  'id' : IDL.Nat,
  'workName' : IDL.Text,
  'workSite' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'email' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'photo' : IDL.Text,
  'employmentStatus' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAdminUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addDocument' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addEmployee' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteAdminUser' : IDL.Func([IDL.Nat], [], []),
  'deleteDocument' : IDL.Func([IDL.Nat], [], []),
  'getAdminUsers' : IDL.Func([], [IDL.Vec(AdminUser)], ['query']),
  'getDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'getDocumentsByEmployee' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'init' : IDL.Func([], [], []),
  'login' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateDocumentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateEmployeeStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdminUser = IDL.Record({
    'id' : IDL.Nat,
    'password' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Document = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'expiryDate' : IDL.Text,
    'fileType' : IDL.Text,
    'employeeId' : IDL.Nat,
    'category' : IDL.Text,
    'uploadDate' : IDL.Text,
  });
  const Employee = IDL.Record({
    'id' : IDL.Nat,
    'workName' : IDL.Text,
    'workSite' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'email' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'photo' : IDL.Text,
    'employmentStatus' : IDL.Text,
  });
  
  return IDL.Service({
    'addAdminUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addDocument' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addEmployee' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteAdminUser' : IDL.Func([IDL.Nat], [], []),
    'deleteDocument' : IDL.Func([IDL.Nat], [], []),
    'getAdminUsers' : IDL.Func([], [IDL.Vec(AdminUser)], ['query']),
    'getDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'getDocumentsByEmployee' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'getEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'init' : IDL.Func([], [], []),
    'login' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateDocumentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateEmployeeStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };