/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminUser {
  'id' : bigint,
  'password' : string,
  'email' : string,
  'phone' : string,
}
export interface Document {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'expiryDate' : string,
  'fileType' : string,
  'employeeId' : bigint,
  'category' : string,
  'uploadDate' : string,
}
export interface Employee {
  'id' : bigint,
  'workName' : string,
  'workSite' : string,
  'name' : string,
  'designation' : string,
  'email' : string,
  'aadhaarNumber' : string,
  'photo' : string,
  'employmentStatus' : string,
}
export interface _SERVICE {
  'addAdminUser' : ActorMethod<[string, string, string], bigint>,
  'addDocument' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    bigint
  >,
  'addEmployee' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    bigint
  >,
  'deleteAdminUser' : ActorMethod<[bigint], undefined>,
  'deleteDocument' : ActorMethod<[bigint], undefined>,
  'deleteEmployee' : ActorMethod<[bigint], undefined>,
  'getAdminUsers' : ActorMethod<[], Array<AdminUser>>,
  'getDocuments' : ActorMethod<[], Array<Document>>,
  'getDocumentsByEmployee' : ActorMethod<[bigint], Array<Document>>,
  'getEmployees' : ActorMethod<[], Array<Employee>>,
  'init' : ActorMethod<[], undefined>,
  'login' : ActorMethod<[string, string, string], boolean>,
  'updateDocumentStatus' : ActorMethod<[bigint, string], undefined>,
  'updateEmployee' : ActorMethod<
    [bigint, string, string, string, string, string, string, string, string],
    undefined
  >,
  'updateEmployeeStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];